name: Crawl Data with Options

on:
    workflow_dispatch:
        inputs:
            options:
                description: The options to pass to the crawler.
                required: false
                default: "-y 111 -t 1 -c 16 -s"

jobs:
    crawl:
        name: Crawl Course Data
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Checkout Data Branch
              uses: actions/checkout@v3
              with:
                  ref: data
                  path: data

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.1
              with:
                  version: latest
                  run-install: false

            - name: Install dependencies
              run: pnpm i

            - name: Crawl data
              run: node dist ${{ github.event.inputs.options }}

            - name: Push to data branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./data"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "data"
                  keep_files: true
