name: Crawl Data

on:
    - workflow_dispatch

jobs:
    crawl:
        name: Crawl Course Data
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm i

            - name: Run
              run: pnpm start

            - name: Push to data branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./data"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "data"
