name: Crawl Data

on:
    - workflow_dispatch

jobs:
    crawl:
        name: Crawl Course Data
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Checkout Data Branch
              uses: actions/checkout@v3
              with:
                  ref: data
                  path: data

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run-install: false

            - name: Install dependencies
              run: pnpm i

            - name: Crawl data (107 ~ 110)
              run: |
                  node dist -y 107 -t 1 -c 16 -s
                  node dist -y 107 -t 2 -c 16 -s
                  node dist -y 108 -t 1 -c 16 -s
                  node dist -y 108 -t 2 -c 16 -s
                  node dist -y 109 -t 1 -c 16 -s
                  node dist -y 109 -t 2 -c 16 -s
                  node dist -y 110 -t 1 -c 16 -s
                  node dist -y 110 -t 2 -c 16 -s

            - name: Push to data branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./data"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "data"
                  keep_files: true
